name: GitHub Pages

on:
  push:
    branches:
      - master # 设置触发工作流的分支，这里是main分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true # 获取所有子模块

      - name: Build the site
        run: |
          npm install -g yarn
          yarn install
          npm run build  # 使用npm构建你的网站
      - name: Deploy the site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用GITHUB_TOKUTN环境变量
          publish_dir: ./dist # 指定要部署的目录
